"""initial_complete_schema

Revision ID: 18145502c704
Revises: 
Create Date: 2026-06-23 18:23:23.107508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18145502c704'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_hash', sa.String(length=64), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), nullable=False),
    sa.Column('topic', sa.String(length=220), nullable=True),
    sa.Column('chapter', sa.String(length=220), nullable=True),
    sa.Column('subject', sa.String(length=80), nullable=True),
    sa.Column('doc_class', sa.String(length=20), nullable=True),
    sa.Column('has_image', sa.Boolean(), nullable=False),
    sa.Column('image_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_hash', name='uq_canonical_hash')
    )
    with op.batch_alter_table('canonical_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canonical_questions_topic'), ['topic'], unique=False)
        batch_op.create_index('ix_cq_chapter', ['chapter'], unique=False)
        batch_op.create_index('ix_cq_difficulty', ['difficulty'], unique=False)
        batch_op.create_index('ix_cq_subject', ['subject'], unique=False)

    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index('ix_chapter_lookup', ['grade', 'subject', 'chapter_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapters_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapters_subject'), ['subject'], unique=False)

    op.create_table('metadata_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('field_value', sa.String(length=220), nullable=False),
    sa.Column('display_label', sa.String(length=220), nullable=False),
    sa.Column('parent_field', sa.String(length=80), nullable=True),
    sa.Column('parent_value', sa.String(length=220), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_name', 'field_value', name='uq_metadata_field_value')
    )
    with op.batch_alter_table('metadata_registry', schema=None) as batch_op:
        batch_op.create_index('ix_mr_field', ['field_name'], unique=False)
        batch_op.create_index('ix_mr_parent', ['parent_field', 'parent_value'], unique=False)

    op.create_table('pdf_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=700), nullable=False),
    sa.Column('file_name', sa.String(length=260), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=80), nullable=True),
    sa.Column('chapter', sa.String(length=220), nullable=True),
    sa.Column('topic', sa.String(length=220), nullable=True),
    sa.Column('source_type', sa.Enum('textbook', 'pyq', 'notes', 'mock_test', 'worksheet', 'reference_material', name='sourcetype'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path', name='uq_pdf_file_path')
    )
    with op.batch_alter_table('pdf_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pdf_metadata_chapter'), ['chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_metadata_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_metadata_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_metadata_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_metadata_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_metadata_year'), ['year'], unique=False)

    op.create_table('question_bank_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=700), nullable=False),
    sa.Column('file_name', sa.String(length=260), nullable=False),
    sa.Column('display_name', sa.String(length=260), nullable=False),
    sa.Column('exam_type', sa.String(length=80), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('total_questions_extracted', sa.Integer(), nullable=False),
    sa.Column('extraction_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='extractionstatus'), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('classification_metadata', sa.JSON(), nullable=True),
    sa.Column('ocr_report', sa.JSON(), nullable=True),
    sa.Column('extraction_report', sa.JSON(), nullable=True),
    sa.Column('database_report', sa.JSON(), nullable=True),
    sa.Column('generated_markdown_path', sa.String(length=700), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    with op.batch_alter_table('question_bank_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_bank_sources_document_hash'), ['document_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_sources_exam_type'), ['exam_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_sources_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_sources_year'), ['year'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'parent', 'admin', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('admin_mock_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('negative_marking', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_event_type'), ['event_type'], unique=False)

    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=80), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('module_slug', sa.String(length=220), nullable=False),
    sa.Column('chapter_title', sa.String(length=220), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module_slug', name='uq_user_module_conv')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conv_user', ['user_id'], unique=False)

    op.create_table('embeddings_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pdf_id', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.String(length=160), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=80), nullable=True),
    sa.Column('chapter', sa.String(length=220), nullable=True),
    sa.Column('topic', sa.String(length=220), nullable=True),
    sa.Column('source_type', sa.Enum('textbook', 'pyq', 'notes', 'mock_test', 'worksheet', 'reference_material', name='sourcetype'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('text_preview', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pdf_id'], ['pdf_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('embeddings_metadata', schema=None) as batch_op:
        batch_op.create_index('ix_embedding_filters', ['grade', 'subject', 'chapter', 'source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_metadata_chapter'), ['chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_metadata_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_metadata_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_metadata_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_metadata_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_metadata_vector_id'), ['vector_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_embeddings_metadata_year'), ['year'], unique=False)

    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=260), nullable=False),
    sa.Column('original_file_name', sa.String(length=260), nullable=False),
    sa.Column('file_path', sa.String(length=700), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('document_type', sa.Enum('pdf', 'docx', 'image', 'txt', name='documenttype'), nullable=False),
    sa.Column('source_type', sa.Enum('textbook', 'pyq', 'notes', 'mock_test', 'worksheet', 'reference_material', name='sourcetype'), nullable=False),
    sa.Column('doc_class', sa.String(length=20), nullable=True),
    sa.Column('doc_subject', sa.String(length=80), nullable=True),
    sa.Column('doc_chapter', sa.String(length=220), nullable=True),
    sa.Column('exam_type', sa.String(length=80), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('processing_status', sa.Enum('queued', 'validating', 'extracting', 'parsing_layout', 'extracting_tables', 'extracting_images', 'chunking', 'deduplicating', 'embedding', 'completed', 'failed', name='processingstatus'), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash', name='uq_knowledge_doc_hash')
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index('ix_kd_metadata_lookup', ['doc_class', 'doc_subject', 'doc_chapter'], unique=False)
        batch_op.create_index('ix_kd_source_type', ['source_type'], unique=False)
        batch_op.create_index('ix_kd_status', ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_doc_chapter'), ['doc_chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_doc_class'), ['doc_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_doc_subject'), ['doc_subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_exam_type'), ['exam_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_uploaded_by_id'), ['uploaded_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_year'), ['year'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('question_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('chapter', sa.String(length=220), nullable=True),
    sa.Column('module', sa.String(length=220), nullable=True),
    sa.Column('question_type', sa.Enum('mcq', 'fill_blank', 'reasoning', name='questiontype'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('textbook_explanation', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source_pdf', sa.String(length=260), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('question_number', sa.Integer(), nullable=True),
    sa.Column('section_name', sa.String(length=220), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('question_source_type', sa.Enum('pdf_extracted', 'manual', 'ai_generated', name='questionsourcetype'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('has_image', sa.Boolean(), nullable=False),
    sa.Column('question_hash', sa.String(length=64), nullable=True),
    sa.Column('table_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['question_bank_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_bank', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_bank_chapter'), ['chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_question_hash'), ['question_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_question_bank_section_name'), ['section_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_year'), ['year'], unique=False)

    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('chapter', sa.String(length=220), nullable=True),
    sa.Column('quiz_type', sa.String(length=80), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('negative_marking', sa.Float(), nullable=False),
    sa.Column('module_order', sa.Integer(), nullable=True),
    sa.Column('quiz_order', sa.Integer(), nullable=True),
    sa.Column('normalized_module_name', sa.String(length=220), nullable=True),
    sa.Column('source_pdf', sa.String(length=260), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quizzes_chapter'), ['chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_normalized_module_name'), ['normalized_module_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_quiz_type'), ['quiz_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_subject'), ['subject'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_exam', sa.String(length=80), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=220), nullable=False),
    sa.Column('school_code', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('medium', sa.String(length=50), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('normalized_school_name', sa.String(length=220), nullable=False),
    sa.Column('normalized_state', sa.String(length=80), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_code'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_normalized_school_name'), ['normalized_school_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_normalized_state'), ['normalized_state'], unique=False)

    op.create_table('study_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_slug', sa.String(length=220), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('chapter_title', sa.String(length=220), nullable=True),
    sa.Column('selected_text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_bookmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_bookmarks_module_slug'), ['module_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_bookmarks_user_id'), ['user_id'], unique=False)

    op.create_table('study_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_slug', sa.String(length=220), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('chapter_title', sa.String(length=220), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('selected_text', sa.Text(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_notes_module_slug'), ['module_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_notes_user_id'), ['user_id'], unique=False)

    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('badge_key', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=260), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_mock_test_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mock_test_id', sa.Integer(), nullable=False),
    sa.Column('participation_rate', sa.Float(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=False),
    sa.Column('school_rankings', sa.JSON(), nullable=True),
    sa.Column('district_rankings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mock_test_id'], ['admin_mock_tests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mock_test_id')
    )
    op.create_table('admin_mock_test_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mock_test_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mock_test_id'], ['admin_mock_tests.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_mock_test_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mock_test_id', sa.Integer(), nullable=False),
    sa.Column('question_bank_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mock_test_id'], ['admin_mock_tests.id'], ),
    sa.ForeignKeyConstraint(['question_bank_id'], ['question_bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_mock_test_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mock_test_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.String(length=220), nullable=False),
    sa.ForeignKeyConstraint(['mock_test_id'], ['admin_mock_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('selected_text', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_citations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=700), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('metadata_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_versions_uploaded_by_id'), ['uploaded_by_id'], unique=False)
        batch_op.create_index('ix_dv_doc', ['document_id'], unique=False)
        batch_op.create_index('ix_dv_version', ['document_id', 'version_number'], unique=False)

    op.create_table('ingestion_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('uploaded', 'validated', 'text_extracted', 'layout_parsed', 'tables_extracted', 'images_extracted', 'vision_processed', 'chunked', 'deduplicated', 'embedded', 'completed', 'failed', 'retried', 'version_created', name='ingestionaction'), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_ial_action', ['action'], unique=False)
        batch_op.create_index('ix_ial_doc', ['document_id'], unique=False)

    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_hash', sa.String(length=64), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_type', sa.Enum('text', 'table', 'image_context', 'equation', 'heading', 'question_block', 'table_chunk', 'image_chunk', name='chunktype'), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('parent_chunk_id', sa.Integer(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('doc_class', sa.String(length=20), nullable=True),
    sa.Column('doc_subject', sa.String(length=80), nullable=True),
    sa.Column('doc_chapter', sa.String(length=220), nullable=True),
    sa.Column('source_type', sa.Enum('textbook', 'pyq', 'notes', 'mock_test', 'worksheet', 'reference_material', name='sourcetype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['knowledge_chunks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_hash', 'document_id', name='uq_chunk_hash_doc')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_kc_doc', ['document_id'], unique=False)
        batch_op.create_index('ix_kc_type', ['chunk_type'], unique=False)

    op.create_table('parent_child_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='linkstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'student_id', name='uq_parent_student')
    )
    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'retrying', 'dead_letter', name='jobstatus'), nullable=False),
    sa.Column('current_stage', sa.String(length=80), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('worker_id', sa.String(length=80), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_pj_doc', ['document_id'], unique=False)
        batch_op.create_index('ix_pj_status_priority', ['status', 'priority'], unique=False)

    op.create_table('progress_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'chapter_id', name='uq_student_chapter_progress')
    )
    op.create_table('question_explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('solution_text', sa.Text(), nullable=False),
    sa.Column('solution_type', sa.String(length=50), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('question_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=700), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_images_question_id'), ['question_id'], unique=False)

    op.create_table('question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('image_path', sa.String(length=700), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_options_question_id'), ['question_id'], unique=False)

    op.create_table('question_source_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('textbook', 'pyq', 'notes', 'mock_test', 'worksheet', 'reference_material', name='sourcetype'), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('question_number', sa.Integer(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['canonical_questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'document_id', name='uq_question_document')
    )
    with op.batch_alter_table('question_source_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_source_links_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_source_links_question_id'), ['question_id'], unique=False)

    op.create_table('question_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('tag_key', sa.String(length=80), nullable=False),
    sa.Column('tag_value', sa.String(length=220), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'tag_key', 'tag_value', name='uq_question_tag')
    )
    with op.batch_alter_table('question_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_tags_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_tags_tag_key'), ['tag_key'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Enum('mcq', 'fill_blank', 'reasoning', name='questiontype'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('textbook_explanation', sa.Text(), nullable=False),
    sa.Column('ai_explanation', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), nullable=False),
    sa.Column('topic', sa.String(length=220), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_topic'), ['topic'], unique=False)

    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_attempt_student_quiz', ['student_id', 'quiz_id'], unique=False)

    op.create_table('quiz_timer_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('remaining_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'quiz_id', name='uq_student_quiz_timer')
    )
    op.create_table('student_module_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('pdf_slug', sa.String(length=220), nullable=False),
    sa.Column('quiz_passed', sa.Boolean(), nullable=False),
    sa.Column('best_accuracy', sa.Float(), nullable=False),
    sa.Column('unlocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'grade', 'subject', 'chapter_number', name='uq_student_module')
    )
    with op.batch_alter_table('student_module_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_module_progress_student_id'), ['student_id'], unique=False)

    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.DateTime(), nullable=False),
    sa.Column('week_end', sa.DateTime(), nullable=False),
    sa.Column('plan_data', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('generated_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.create_index('ix_study_plan_student_active', ['student_id', 'is_active'], unique=False)

    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=True),
    sa.Column('chapter', sa.String(length=220), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_sessions_student_id'), ['student_id'], unique=False)

    op.create_table('knowledge_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.String(length=160), nullable=False),
    sa.Column('collection_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', name='uq_ke_chunk_id'),
    sa.UniqueConstraint('vector_id', name='uq_ke_vector_id')
    )
    op.create_table('knowledge_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('image_index', sa.Integer(), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('image_path', sa.String(length=700), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('figure', 'diagram', 'graph', 'flowchart', 'map', 'geometry_figure', 'scientific_illustration', 'labeled_image', 'question_figure', 'generic', name='visioncontenttype'), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('detected_text', sa.Text(), nullable=False),
    sa.Column('vision_context', sa.Text(), nullable=False),
    sa.Column('concepts', sa.JSON(), nullable=True),
    sa.Column('objects_detected', sa.JSON(), nullable=True),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_hash', 'document_id', name='uq_image_doc')
    )
    with op.batch_alter_table('knowledge_images', schema=None) as batch_op:
        batch_op.create_index('ix_ki_doc', ['document_id'], unique=False)
        batch_op.create_index('ix_ki_page', ['document_id', 'page_number'], unique=False)

    op.create_table('knowledge_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('table_index', sa.Integer(), nullable=False),
    sa.Column('table_hash', sa.String(length=64), nullable=False),
    sa.Column('table_json', sa.JSON(), nullable=False),
    sa.Column('table_markdown', sa.Text(), nullable=False),
    sa.Column('table_text', sa.Text(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('col_count', sa.Integer(), nullable=False),
    sa.Column('extraction_method', sa.String(length=20), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_hash', 'document_id', name='uq_table_doc')
    )
    with op.batch_alter_table('knowledge_tables', schema=None) as batch_op:
        batch_op.create_index('ix_kt_doc', ['document_id'], unique=False)
        batch_op.create_index('ix_kt_page', ['document_id', 'page_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_tables', schema=None) as batch_op:
        batch_op.drop_index('ix_kt_page')
        batch_op.drop_index('ix_kt_doc')

    op.drop_table('knowledge_tables')
    with op.batch_alter_table('knowledge_images', schema=None) as batch_op:
        batch_op.drop_index('ix_ki_page')
        batch_op.drop_index('ix_ki_doc')

    op.drop_table('knowledge_images')
    op.drop_table('knowledge_embeddings')
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_sessions_student_id'))

    op.drop_table('study_sessions')
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.drop_index('ix_study_plan_student_active')

    op.drop_table('study_plans')
    with op.batch_alter_table('student_module_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_module_progress_student_id'))

    op.drop_table('student_module_progress')
    op.drop_table('quiz_timer_states')
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_attempt_student_quiz')

    op.drop_table('quiz_attempts')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_topic'))

    op.drop_table('questions')
    with op.batch_alter_table('question_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_tags_tag_key'))
        batch_op.drop_index(batch_op.f('ix_question_tags_question_id'))

    op.drop_table('question_tags')
    with op.batch_alter_table('question_source_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_source_links_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_source_links_document_id'))

    op.drop_table('question_source_links')
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_options_question_id'))

    op.drop_table('question_options')
    with op.batch_alter_table('question_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_images_question_id'))

    op.drop_table('question_images')
    op.drop_table('question_explanations')
    op.drop_table('progress_tracking')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_pj_status_priority')
        batch_op.drop_index('ix_pj_doc')

    op.drop_table('processing_jobs')
    op.drop_table('parent_child_links')
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index('ix_kc_type')
        batch_op.drop_index('ix_kc_doc')

    op.drop_table('knowledge_chunks')
    with op.batch_alter_table('ingestion_audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_ial_doc')
        batch_op.drop_index('ix_ial_action')

    op.drop_table('ingestion_audit_logs')
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_dv_version')
        batch_op.drop_index('ix_dv_doc')
        batch_op.drop_index(batch_op.f('ix_document_versions_uploaded_by_id'))

    op.drop_table('document_versions')
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_messages_conversation_id'))

    op.drop_table('conversation_messages')
    op.drop_table('admin_mock_test_targets')
    op.drop_table('admin_mock_test_questions')
    op.drop_table('admin_mock_test_attempts')
    op.drop_table('admin_mock_test_analytics')
    op.drop_table('achievements')
    with op.batch_alter_table('study_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_notes_module_slug'))

    op.drop_table('study_notes')
    with op.batch_alter_table('study_bookmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_bookmarks_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_bookmarks_module_slug'))

    op.drop_table('study_bookmarks')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_normalized_state'))
        batch_op.drop_index(batch_op.f('ix_students_normalized_school_name'))

    op.drop_table('students')
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quizzes_subject'))
        batch_op.drop_index(batch_op.f('ix_quizzes_quiz_type'))
        batch_op.drop_index(batch_op.f('ix_quizzes_normalized_module_name'))
        batch_op.drop_index(batch_op.f('ix_quizzes_grade'))
        batch_op.drop_index(batch_op.f('ix_quizzes_chapter'))

    op.drop_table('quizzes')
    with op.batch_alter_table('question_bank', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_bank_year'))
        batch_op.drop_index(batch_op.f('ix_question_bank_subject'))
        batch_op.drop_index(batch_op.f('ix_question_bank_source_id'))
        batch_op.drop_index(batch_op.f('ix_question_bank_section_name'))
        batch_op.drop_index(batch_op.f('ix_question_bank_question_hash'))
        batch_op.drop_index(batch_op.f('ix_question_bank_module'))
        batch_op.drop_index(batch_op.f('ix_question_bank_grade'))
        batch_op.drop_index(batch_op.f('ix_question_bank_chapter'))

    op.drop_table('question_bank')
    op.drop_table('parents')
    op.drop_table('notifications')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_year'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_uploaded_by_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_exam_type'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_doc_subject'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_doc_class'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_doc_chapter'))
        batch_op.drop_index('ix_kd_status')
        batch_op.drop_index('ix_kd_source_type')
        batch_op.drop_index('ix_kd_metadata_lookup')

    op.drop_table('knowledge_documents')
    with op.batch_alter_table('embeddings_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embeddings_metadata_year'))
        batch_op.drop_index(batch_op.f('ix_embeddings_metadata_vector_id'))
        batch_op.drop_index(batch_op.f('ix_embeddings_metadata_topic'))
        batch_op.drop_index(batch_op.f('ix_embeddings_metadata_subject'))
        batch_op.drop_index(batch_op.f('ix_embeddings_metadata_source_type'))
        batch_op.drop_index(batch_op.f('ix_embeddings_metadata_grade'))
        batch_op.drop_index(batch_op.f('ix_embeddings_metadata_chapter'))
        batch_op.drop_index('ix_embedding_filters')

    op.drop_table('embeddings_metadata')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conv_user')

    op.drop_table('conversations')
    op.drop_table('announcements')
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_event_type'))

    op.drop_table('analytics')
    op.drop_table('ai_conversations')
    op.drop_table('admin_mock_tests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('question_bank_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_bank_sources_year'))
        batch_op.drop_index(batch_op.f('ix_question_bank_sources_grade'))
        batch_op.drop_index(batch_op.f('ix_question_bank_sources_exam_type'))
        batch_op.drop_index(batch_op.f('ix_question_bank_sources_document_hash'))

    op.drop_table('question_bank_sources')
    with op.batch_alter_table('pdf_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pdf_metadata_year'))
        batch_op.drop_index(batch_op.f('ix_pdf_metadata_topic'))
        batch_op.drop_index(batch_op.f('ix_pdf_metadata_subject'))
        batch_op.drop_index(batch_op.f('ix_pdf_metadata_source_type'))
        batch_op.drop_index(batch_op.f('ix_pdf_metadata_grade'))
        batch_op.drop_index(batch_op.f('ix_pdf_metadata_chapter'))

    op.drop_table('pdf_metadata')
    with op.batch_alter_table('metadata_registry', schema=None) as batch_op:
        batch_op.drop_index('ix_mr_parent')
        batch_op.drop_index('ix_mr_field')

    op.drop_table('metadata_registry')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapters_subject'))
        batch_op.drop_index(batch_op.f('ix_chapters_grade'))
        batch_op.drop_index('ix_chapter_lookup')

    op.drop_table('chapters')
    with op.batch_alter_table('canonical_questions', schema=None) as batch_op:
        batch_op.drop_index('ix_cq_subject')
        batch_op.drop_index('ix_cq_difficulty')
        batch_op.drop_index('ix_cq_chapter')
        batch_op.drop_index(batch_op.f('ix_canonical_questions_topic'))

    op.drop_table('canonical_questions')
    # ### end Alembic commands ###
