"""Add question extraction pipeline columns

Revision ID: 7ae92e94cc3d
Revises: b7a9f3c2f1f4
Create Date: 2026-06-22 22:08:47.553193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7ae92e94cc3d'
down_revision: Union[str, None] = 'b7a9f3c2f1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_bank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('table_data', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_question_bank_question_hash'), ['question_hash'], unique=True)

    with op.batch_alter_table('question_bank_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('classification_metadata', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ocr_report', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('extraction_report', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('database_report', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('generated_markdown_path', sa.String(length=700), nullable=True))
        batch_op.create_index(batch_op.f('ix_question_bank_sources_document_hash'), ['document_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_bank_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_bank_sources_document_hash'))
        batch_op.drop_column('generated_markdown_path')
        batch_op.drop_column('database_report')
        batch_op.drop_column('extraction_report')
        batch_op.drop_column('ocr_report')
        batch_op.drop_column('classification_metadata')
        batch_op.drop_column('document_hash')

    with op.batch_alter_table('question_bank', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_bank_question_hash'))
        batch_op.drop_column('table_data')
        batch_op.drop_column('question_hash')
    # ### end Alembic commands ###

