"""Add video_recommendations

Revision ID: b0a192c3a870
Revises: 18145502c704
Create Date: 2026-06-27 15:33:39.355104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0a192c3a870'
down_revision: Union[str, None] = '18145502c704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('video_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('thumbnail', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_recommendations_chapter_id'), ['chapter_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_recommendations_chapter_id'))

    op.drop_table('video_recommendations')
    # ### end Alembic commands ###
