"""Initial Schema

Revision ID: ee1856674737
Revises: 
Create Date: 2026-05-24 16:03:35.228558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1856674737'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index('ix_chapter_lookup', ['grade', 'subject', 'chapter_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapters_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapters_subject'), ['subject'], unique=False)

    op.create_table('pdf_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=700), nullable=False),
    sa.Column('file_name', sa.String(length=260), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=80), nullable=True),
    sa.Column('chapter', sa.String(length=220), nullable=True),
    sa.Column('topic', sa.String(length=220), nullable=True),
    sa.Column('source_type', sa.Enum('textbook', 'pyq', 'notes', name='sourcetype'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path', name='uq_pdf_file_path')
    )
    with op.batch_alter_table('pdf_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pdf_metadata_chapter'), ['chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_metadata_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_metadata_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_metadata_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_metadata_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_metadata_year'), ['year'], unique=False)

    op.create_table('question_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('chapter', sa.String(length=220), nullable=True),
    sa.Column('module', sa.String(length=220), nullable=True),
    sa.Column('question_type', sa.Enum('mcq', 'fill_blank', 'reasoning', name='questiontype'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('textbook_explanation', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source_pdf', sa.String(length=260), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_bank', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_bank_chapter'), ['chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bank_subject'), ['subject'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'parent', 'admin', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('admin_mock_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('negative_marking', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_event_type'), ['event_type'], unique=False)

    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=80), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embeddings_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pdf_id', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.String(length=160), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=80), nullable=True),
    sa.Column('chapter', sa.String(length=220), nullable=True),
    sa.Column('topic', sa.String(length=220), nullable=True),
    sa.Column('source_type', sa.Enum('textbook', 'pyq', 'notes', name='sourcetype'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('text_preview', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pdf_id'], ['pdf_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('embeddings_metadata', schema=None) as batch_op:
        batch_op.create_index('ix_embedding_filters', ['grade', 'subject', 'chapter', 'source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_metadata_chapter'), ['chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_metadata_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_metadata_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_metadata_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_metadata_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_metadata_vector_id'), ['vector_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_embeddings_metadata_year'), ['year'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('chapter', sa.String(length=220), nullable=True),
    sa.Column('quiz_type', sa.String(length=80), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('module_order', sa.Integer(), nullable=True),
    sa.Column('quiz_order', sa.Integer(), nullable=True),
    sa.Column('normalized_module_name', sa.String(length=220), nullable=True),
    sa.Column('source_pdf', sa.String(length=260), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quizzes_chapter'), ['chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_normalized_module_name'), ['normalized_module_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_quiz_type'), ['quiz_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_subject'), ['subject'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_exam', sa.String(length=80), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=220), nullable=False),
    sa.Column('school_code', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('medium', sa.String(length=50), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('normalized_school_name', sa.String(length=220), nullable=False),
    sa.Column('normalized_state', sa.String(length=80), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_code'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_normalized_school_name'), ['normalized_school_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_normalized_state'), ['normalized_state'], unique=False)

    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('badge_key', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=260), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_mock_test_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mock_test_id', sa.Integer(), nullable=False),
    sa.Column('participation_rate', sa.Float(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=False),
    sa.Column('school_rankings', sa.JSON(), nullable=True),
    sa.Column('district_rankings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mock_test_id'], ['admin_mock_tests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mock_test_id')
    )
    op.create_table('admin_mock_test_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mock_test_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mock_test_id'], ['admin_mock_tests.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_mock_test_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mock_test_id', sa.Integer(), nullable=False),
    sa.Column('question_bank_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mock_test_id'], ['admin_mock_tests.id'], ),
    sa.ForeignKeyConstraint(['question_bank_id'], ['question_bank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_mock_test_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mock_test_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.String(length=220), nullable=False),
    sa.ForeignKeyConstraint(['mock_test_id'], ['admin_mock_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_child_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='linkstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'student_id', name='uq_parent_student')
    )
    op.create_table('progress_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'chapter_id', name='uq_student_chapter_progress')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Enum('mcq', 'fill_blank', 'reasoning', name='questiontype'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('textbook_explanation', sa.Text(), nullable=False),
    sa.Column('ai_explanation', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), nullable=False),
    sa.Column('topic', sa.String(length=220), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_topic'), ['topic'], unique=False)

    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_attempt_student_quiz', ['student_id', 'quiz_id'], unique=False)

    op.create_table('quiz_timer_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('remaining_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'quiz_id', name='uq_student_quiz_timer')
    )
    op.create_table('student_module_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('pdf_slug', sa.String(length=220), nullable=False),
    sa.Column('quiz_passed', sa.Boolean(), nullable=False),
    sa.Column('best_accuracy', sa.Float(), nullable=False),
    sa.Column('unlocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'grade', 'subject', 'chapter_number', name='uq_student_module')
    )
    with op.batch_alter_table('student_module_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_module_progress_student_id'), ['student_id'], unique=False)

    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=True),
    sa.Column('chapter', sa.String(length=220), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_sessions_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_sessions_student_id'))

    op.drop_table('study_sessions')
    with op.batch_alter_table('student_module_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_module_progress_student_id'))

    op.drop_table('student_module_progress')
    op.drop_table('quiz_timer_states')
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_attempt_student_quiz')

    op.drop_table('quiz_attempts')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_topic'))

    op.drop_table('questions')
    op.drop_table('progress_tracking')
    op.drop_table('parent_child_links')
    op.drop_table('admin_mock_test_targets')
    op.drop_table('admin_mock_test_questions')
    op.drop_table('admin_mock_test_attempts')
    op.drop_table('admin_mock_test_analytics')
    op.drop_table('achievements')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_normalized_state'))
        batch_op.drop_index(batch_op.f('ix_students_normalized_school_name'))

    op.drop_table('students')
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quizzes_subject'))
        batch_op.drop_index(batch_op.f('ix_quizzes_quiz_type'))
        batch_op.drop_index(batch_op.f('ix_quizzes_normalized_module_name'))
        batch_op.drop_index(batch_op.f('ix_quizzes_grade'))
        batch_op.drop_index(batch_op.f('ix_quizzes_chapter'))

    op.drop_table('quizzes')
    op.drop_table('parents')
    op.drop_table('notifications')
    with op.batch_alter_table('embeddings_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embeddings_metadata_year'))
        batch_op.drop_index(batch_op.f('ix_embeddings_metadata_vector_id'))
        batch_op.drop_index(batch_op.f('ix_embeddings_metadata_topic'))
        batch_op.drop_index(batch_op.f('ix_embeddings_metadata_subject'))
        batch_op.drop_index(batch_op.f('ix_embeddings_metadata_source_type'))
        batch_op.drop_index(batch_op.f('ix_embeddings_metadata_grade'))
        batch_op.drop_index(batch_op.f('ix_embeddings_metadata_chapter'))
        batch_op.drop_index('ix_embedding_filters')

    op.drop_table('embeddings_metadata')
    op.drop_table('announcements')
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_event_type'))

    op.drop_table('analytics')
    op.drop_table('ai_conversations')
    op.drop_table('admin_mock_tests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('question_bank', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_bank_subject'))
        batch_op.drop_index(batch_op.f('ix_question_bank_module'))
        batch_op.drop_index(batch_op.f('ix_question_bank_grade'))
        batch_op.drop_index(batch_op.f('ix_question_bank_chapter'))

    op.drop_table('question_bank')
    with op.batch_alter_table('pdf_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pdf_metadata_year'))
        batch_op.drop_index(batch_op.f('ix_pdf_metadata_topic'))
        batch_op.drop_index(batch_op.f('ix_pdf_metadata_subject'))
        batch_op.drop_index(batch_op.f('ix_pdf_metadata_source_type'))
        batch_op.drop_index(batch_op.f('ix_pdf_metadata_grade'))
        batch_op.drop_index(batch_op.f('ix_pdf_metadata_chapter'))

    op.drop_table('pdf_metadata')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapters_subject'))
        batch_op.drop_index(batch_op.f('ix_chapters_grade'))
        batch_op.drop_index('ix_chapter_lookup')

    op.drop_table('chapters')
    # ### end Alembic commands ###
