export const class9MathModules = [
  { title: "Number System and Operations", slug: "chapter-1-nsao" },
  { title: "Quadrilaterals", slug: "chapter-2-quadrilaterals" },
  { title: "Statistics", slug: "chapter-3-statistics" },
  { title: "Trigonometry", slug: "chapter-4-trigonometry" },
  { title: "Square and Square Roots", slug: "chapter-5-square-and-square-roots" },
  { title: "Cube and Cube Roots", slug: "chapter-6-cube-and-cube-roots" },
  { title: "Comparing Quantities", slug: "chapter-7-comparing-quantities" },
  { title: "Algebraic Expressions Identities", slug: "chapter-8-algebraic-expression-identities" },
  { title: "Solid Shapes", slug: "chapter-9-solid-shapes" },
  { title: "Mensuration", slug: "chapter-10-mensuration" },
  { title: "Exponents", slug: "chapter-11-exponents" },
  { title: "Direct Inverse Proportional", slug: "chapter-12-direct-inverse-proportional" },
  { title: "Factorization", slug: "chapter-13-factorization" },
  { title: "Rational Numbers", slug: "chapter-14-rational-numbers" },
  { title: "Linear Equations in one Variable", slug: "chapter-15-linear-equations-in-one-variable" },
  { title: "Percentage Profit and Loss", slug: "chapter-16-percentage-profit-and-loss" },
  { title: "Algebra", slug: "chapter-17-algebra" },
  { title: "Geometry", slug: "chapter-18-geometry" }
];

export const class9ScienceModules = [
  { title: "Magnetism", slug: "chapter-1-magnetism" },
  { title: "Population", slug: "chapter-2-population" },
  { title: "Tissue", slug: "chapter-3-tissue" },
  { title: "Acids, Bases and Salts", slug: "chapter-4-acids, bases and salts" },
  { title: "Environment", slug: "chapter-5-environment" },
  { title: "Electricity", slug: "chapter-6-electricity" },
  { title: "Sources of Energy", slug: "chapter-7-sources of energy" },
  { title: "Crop Production and Microorganisms", slug: "chapter-8-crop production and microorganisms" },
  { title: "Microorganisms", slug: "chapter-9-microorganisms" },
  { title: "Conservation of Plants and Animals", slug: "chapter-10-conservation of plants and animals" },
  { title: "Cell", slug: "chapter-11-cell" },
  { title: "Reproduction", slug: "chapter-12-reproduction" },
  { title: "Synthetic Fibres and Plastics", slug: "chapter-13-synthetic fibres and plastics" },
  { title: "Metals and Non Metals", slug: "chapter-14-metals and non metals" },
  { title: "Coal and Petroleum", slug: "chapter-15-coal and petroleum" },
  { title: "Carbon", slug: "chapter-16-carbon" },
  { title: "Pollution", slug: "chapter-17-pollution" },
  { title: "Pollution of Air and Water", slug: "chapter-18-pollution of air and water" },
  { title: "Air", slug: "chapter-19-air" },
  { title: "Motion, Force, Work and Energy", slug: "chapter-20-motion force work and energy" },
  { title: "Light", slug: "chapter-21-light" },
  { title: "Universe", slug: "chapter-22-universe" },
  { title: "Heat", slug: "chapter-23-heat" },
  { title: "Simple Machine", slug: "chapter-24-simple machine" },
  { title: "Advance Physics", slug: "chapter-25-advance physics" },
  { title: "Nitrogen Oxygen Fire Extinguisher and Buoyancy", slug: "chapter-26-Nitrogen Oxygen Fire Extinguisher and Buoyancy" },
  { title: "Transformation of Substance", slug: "chapter-27-Transformation of Substance" },
  { title: "Adaptations", slug: "chapter-28-Adaptations" },
  { title: "Diseases", slug: "chapter-29-Diseases" },
  { title: "Transportation", slug: "chapter-30-Transportation" },
  { title: "Excretion", slug: "chapter-31-Excretion" },
  { title: "Skeletal System", slug: "chapter-32-Skeletal System" },
  { title: "Respiration", slug: "chapter-33-Respiration" },
  { title: "Heredity and Variations", slug: "chapter-34-Heredity and Variations" },
  { title: "Origin of Life", slug: "chapter-35-Origin of Life" },
  { title: "Control and Co-ordination", slug: "chapter-36-Control and Co-ordination" },
  { title: "Diversity of Living Organism", slug: "chapter-37-Diversity of Living Organism" },
  { title: "Nutrition", slug: "chapter-38-Nutrition" },
  { title: "Food", slug: "chapter-39-Food" },
  { title: "Structure of Atom and Chemical Bonding", slug: "chapter-40-Structure of Atom and Chemical Bonding" }
];

export const class9EnglishModules = [
  { title: "Noun", slug: "chapter-1-Noun" },
  { title: "Pronoun", slug: "chapter-2-Pronoun" },
  { title: "Jumbled Words and Sentences", slug: "chapter-3-Jumbled Words and Sentences" },
  { title: "Verb", slug: "chapter-4-Verb" },
  { title: "Preposition", slug: "chapter-5-Preposition" },
  { title: "Articles", slug: "chapter-6-Articles" },
  { title: "Antonyms OR Synonyms", slug: "chapter-7-Antonyms OR Synonyms" },
  { title: "Comprehension", slug: "chapter-8-Comprehension" },
  { title: "Conjunction", slug: "chapter-9-Conjunction" },
  { title: "Tense", slug: "chapter-10-Tense" },
  { title: "Analogy", slug: "chapter-11-Analogy" },
  { title: "Types of Sentence", slug: "chapter-12-Types of Sentence" },
  { title: "Letters", slug: "chapter-13-Letters" },
  { title: "Modals", slug: "chapter-14-Modals" },
  { title: "Determiners", slug: "chapter-15-Determiners" },
  { title: "Voice", slug: "chapter-16-Voice" },
  { title: "Narration", slug: "chapter-17-Narration" },
  { title: "Clauses", slug: "chapter-18-Clauses" }
];

export const modulesMap = {
  maths: class9MathModules,
  science: class9ScienceModules,
  english: class9EnglishModules
};
